[project]
name = "01-swap-case"
version = "0.1.0"
description = "A Python project to implement a swap case function."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=1.24.0"
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.5",
]
