name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  run-challenges:
    name: Run Challenges
    runs-on: ubuntu-latest
    strategy:
      matrix:
        challenge:
          - "01_swap_case"
          - "02_find_a_string"
          - "03_symmetric_difference"
          - "04_longest_consecutive_sequence"
          - "05_merge_the_tools"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install required version defined in pyproject.toml
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "week-1/challenges/rafatedesco_python/${{ matrix.challenge }}/pyproject.toml"
      - name: Install dependencies
        run: |
          cd "week-1/challenges/rafatedesco_python/${{ matrix.challenge }}"
          uv sync
      - name: Run tests
        run: |
          cd "week-1/challenges/rafatedesco_python/${{ matrix.challenge }}"
          uv run pytest tests