name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  challenge-01:
    name: Challenge 01 - Swap Case
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install required version defined in pyproject.toml
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: "week-1/challenges/rafatedesco_python/01_swap_case/pyproject.toml"
      - name: Install dependencies
        run: |
          uv sync
      - name: Run tests
        run: |
          uv run pytest week-1/challenges/rafatedesco_python/01_swap_case/tests
